name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages  # Especifica el entorno aquí

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate .env/stg.json
        run: |
          mkdir -p .env
          echo '{
            "ENV": "${{ vars.ENV }}",
            "SERVERIP": "${{ vars.SERVERIP }}",
            "SERVERIP_LOCAL": "${{ vars.SERVERIP_LOCAL }}",
            "SERVERIP_LOCAL_WEB": "${{ vars.SERVERIP_LOCAL_WEB }}",
            "FIREBASE_IMAGE_PATH_PET": "${{ vars.FIREBASE_IMAGE_PATH_PET }}",
            "FIREBASE_IMAGE_PATH_USER": "${{ vars.FIREBASE_IMAGE_PATH_USER }}",
            "FIREBASE_DOCS_PATH": "${{ vars.FIREBASE_DOCS_PATH }}",
            "PAYU_PAYMENT_URL": "${{ vars.PAYU_PAYMENT_URL }}",
            "PAYMENT_REPONSE_PAGE": "${{ vars.PAYMENT_REPONSE_PAGE }}",
            "PAYMENT_CONFIRMATION_PAGE": "${{ vars.PAYMENT_CONFIRMATION_PAGE }}",
            "FIREBASE_WEB_API_KEY": "${{ secrets.FIREBASE_WEB_API_KEY }}",
            "FIREBASE_WEB_VAPID_KEY": "${{ secrets.FIREBASE_WEB_VAPID_KEY }}",
            "GOOGLE_PLACES_API_KEY": "${{ secrets.GOOGLE_PLACES_API_KEY }}"
          }' > .env/stg.json

      - name: Copy compiled web app
        run: |
          mkdir -p build/web
          cp -r .env build/web/.env
          cp -r $(ls -A | grep -v build) build/web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
