name: Environment Variables

on:
  workflow_dispatch:

env:
  ENV: ${{ vars.ENV }}
  SERVERIP: ${{ vars.SERVERIP }}
  SERVERIP_LOCAL: ${{ vars.SERVERIP_LOCAL }}
  SERVERIP_LOCAL_WEB: ${{ vars.SERVERIP_LOCAL_WEB }}
  FIREBASE_IMAGE_PATH_PET: ${{ vars.FIREBASE_IMAGE_PATH_PET }}
  FIREBASE_IMAGE_PATH_USER: ${{ vars.FIREBASE_IMAGE_PATH_USER }}
  FIREBASE_DOCS_PATH: ${{ vars.FIREBASE_DOCS_PATH }}
  PAYU_PAYMENT_URL: ${{ vars.PAYU_PAYMENT_URL }}
  PAYMENT_REPONSE_PAGE: ${{ vars.PAYMENT_REPONSE_PAGE }}
  PAYMENT_CONFIRMATION_PAGE: ${{ vars.PAYMENT_CONFIRMATION_PAGE }}
  FIREBASE_WEB_API_KEY: ${{ secrets.FIREBASE_WEB_API_KEY }}
  FIREBASE_WEB_VAPID_KEY: ${{ secrets.FIREBASE_WEB_VAPID_KEY }}
  GOOGLE_PLACES_API_KEY: ${{ secrets.GOOGLE_PLACES_API_KEY }}

jobs:
  variables_secrets:
    name: Variables and Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Web Api Key Secret
        run: echo ${{ secrets.FIREBASE_WEB_API_KEY }}

      - name: Ambiente
        run: echo "$env.ENV"

      - name: List Environment Variables
        run: env

      - name: Fin
        run: echo "Fin del proceso"
