name: Environment Variables

on:
  workflow_dispatch:

jobs:
  variables_secrets:
    name: Variables and Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Web Api Key Secret
        run: echo ${{ secrets.FIREBASE_WEB_API_KEY }}
      - name: Fin
      - run: echo "Fin del job de prueba "


